services:
  bind:
    build: ./bind
    container_name: lucos_dns_bind
    ports:
      - "53:53"
      - "53:53/udp"
    image: lucas42/lucos_dns_bind:${VERSION:-latest}
    restart: always
    environment:
      - TSIG_SECRET
    volumes:
      - "generatedzones:/etc/bind/generated-zones/"
    healthcheck:
      test: ["CMD-SHELL", "dig @127.0.0.1 localhost +short > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  sync:
    build: ./sync
    container_name: lucos_dns_sync
    image: lucas42/lucos_dns_sync:${VERSION:-latest}
    restart: always
    environment:
      - SYSTEM
      - LOGANNE_ENDPOINT
      - SCHEDULE_TRACKER_ENDPOINT
      - CONFIGY_ENDPOINT
      - ZONES_PATH=/etc/bind/generated-zones/
    volumes:
      - "generatedzones:/etc/bind/generated-zones/"
    healthcheck:
      test: ["CMD-SHELL", "ps | grep -q '[s]upercronic'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  generatedzones:

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:2::/64
